### ISSUE TITLE
Problem with 'alias_method_chain' when using Rails 5.2.1

### ISSUE THREAD

**Issue by ianeinser** [cthulhu666/easy_table#16]
Hello there,

i got an error when using Rails 5.2.1. Would you please update your gem? I really appreciate it. Thanks

NoMethodError: undefined method `alias_method_chain' for EasyTable::Components::Columns:Module
Did you mean?  alias_method

**Comment by cthulhu666** [comment]
@ianeinser thanks for your report, I will look into it.

**Comment by cthulhu666** [comment]
@ianeinser could you please paste the whole stacktrace?

**Comment by ianeinser** [comment]
> @ianeinser could you please paste the whole stacktrace?

Step 17/22 : RUN echo "# This file was overridden by default during docker image build." > Gemfile.plugin   && ./bin/init_config   && chmod +x ./bin/logger   && bundle exec rake tmp:create   && bundle exec rake yarn:install assets:precompile
 ---> Running in af7604859071
Copy /home/app/config/templates/management_api_v1.yml.erb -> /home/app/config/management_api_v1.yml
Copy /home/app/config/templates/seed/blockchains.yml.erb -> /home/app/config/seed/blockchains.yml
Copy /home/app/config/templates/seed/wallets.yml.erb -> /home/app/config/seed/wallets.yml
Copy /home/app/config/templates/seed/markets.yml.erb -> /home/app/config/seed/markets.yml
Copy /home/app/config/templates/seed/currencies.yml.erb -> /home/app/config/seed/currencies.yml
Copy /home/app/config/templates/plugins.yml.erb -> /home/app/config/plugins.yml
Copy /home/app/config/templates/application.yml.erb -> /home/app/config/application.yml
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)mkdir -p tmp/cache
mkdir -p tmp/sockets
mkdir -p tmp/pids
mkdir -p tmp/cache/assets
/opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.05s.
rake aborted!
NoMethodError: undefined method `alias_method_chain' for EasyTable::Components::Columns:Module
Did you mean?  alias_method
/home/app/config/initializers/easy_table.rb:21:in `<module:Columns>'
/home/app/config/initializers/easy_table.rb:6:in `<module:Components>'
/home/app/config/initializers/easy_table.rb:5:in `<module:EasyTable>'
/home/app/config/initializers/easy_table.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
/home/app/config/environment.rb:8:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:337:in `require_environment!'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)

**Comment by cthulhu666** [comment]
@ianeinser 
thank you
It looks like the exception is raised not in gem code, but in some application code:
```
/home/app/config/initializers/easy_table.rb:21
```
could you perhaps paste this file here, or at least some relevant part?

**Comment by ianeinser** [comment]
# encoding: UTF-8
# frozen_string_literal: true

module EasyTable
  module Components
    module Columns
      def column_with_custom(title, label_or_opts = nil, opts = {}, &block)
        if @options[:model]
          label_or_opts ||= {}
          label_or_opts.merge!({model: @options[:model]})
        end

        if @options[:scope]
          label_or_opts ||= {}
          label_or_opts.merge!({scope: @options[:scope]})
        end

        column_without_custom(title, label_or_opts, opts, &block)
      end

      alias_method_chain :column, :custom  
    end

    module Base
      def translate_with_custom(key)
        if @opts[:model]
          @opts[:model].human_attribute_name(@title)
        elsif @opts[:scope]
          I18n.t("easy_table.#{@opts[:scope]}.#{@title}")
        else
          translate_without_custom(key)
        end
      end

      alias_method_chain :translate, :custom  
    end
  end
end

**Comment by ianeinser** [comment]
Hi.. this is the file

# encoding: UTF-8
# frozen_string_literal: true

module EasyTable
  module Components
    module Columns
      def column_with_custom(title, label_or_opts = nil, opts = {}, &block)
        if @options[:model]
          label_or_opts ||= {}
          label_or_opts.merge!({model: @options[:model]})
        end

        if @options[:scope]
          label_or_opts ||= {}
          label_or_opts.merge!({scope: @options[:scope]})
        end

        column_without_custom(title, label_or_opts, opts, &block)
      end

      alias_method_chain :column, :custom  
    end

    module Base
      def translate_with_custom(key)
        if @opts[:model]
          @opts[:model].human_attribute_name(@title)
        elsif @opts[:scope]
          I18n.t("easy_table.#{@opts[:scope]}.#{@title}")
        else
          translate_without_custom(key)
        end
      end

      alias_method_chain :translate, :custom  
    end
  end
end

**Comment by cthulhu666** [comment]
@ianeinser OK, so as you can see it's an exception raised in your application code.
`alias_method_chain` is clearly deprecated.
Read more e.g. https://blog.bigbinary.com/2016/08/21/rails-5-deprecates-alias-method-chain.html

**Comment by ianeinser** [comment]
> @ianeinser OK, so as you can see it's an exception raised in your application code.
> `alias_method_chain` is clearly deprecated.
> Read more e.g. https://blog.bigbinary.com/2016/08/21/rails-5-deprecates-alias-method-chain.html

Hello,
thanks for the pointer. I got the source code from other developer. Can you help me to re-code so that it doesn't use alias_method_chain anymore in that case. 

regards
