### ISSUE TITLE
Bump RubyTree version?

### ISSUE THREAD

**Issue by JeremyRubin** [cthulhu666/easy_table#6]
Possible to bump the rubytree version from the gemspec to the most recent release?

**Comment by cthulhu666** [comment]
Hi
sure!
I've just pushed an update to master, please let me know if it works for you - I will prepare a new release soon, I need to take care of some warnings that show during tests prior to releasing new version.

**Comment by JeremyRubin** [comment]
Looks good to me!

**Comment by cthulhu666** [comment]
Version `0.0.9` relased and published to rubygems.org
